### ISSUE TITLE
Define interface as abstraction layer for storing tasks

### ISSUE THREAD

**Issue by tpeetz** [tpeetz/pull-task#11]
Define interface to build abstraction layer for storing tasks.
The tasks should contain all necessary information.

There will be a struct for every type of Gitserver which implement
the according data manipulation rules.

**Comment by thatnerdjosh** [comment]
Does it make sense to have `git` itself as a backend for something like https://github.com/naggie/dstask

Also, do you think it makes sense to extract common packages, and add a repo for a tool such as `push-task`?
